### ISSUE TITLE
The aspect ratio is same on fullscreen

### ISSUE THREAD

**Issue by ayushmng** [one-am-it/react-native-simple-image-slider#2]
When I open the image in fullScreen mode, it maintains the same cropped aspect ratio. Is it possible to assign a different aspect ratio to the image when viewed in fullscreen?

**Comment by david98** [comment]
Hey, thanks for trying this 😄 Unfortunately, I didn't really think about that while developing this slider, I'll take a look ASAP and try to provide a way to customize the full screen appearance separately.

**Comment by ayushmng** [comment]
Thank you so much for your prompt response and attention to this matter, the customization on the full screen really means a lot to me, and I'll be waiting for this update😊. Also, setting `fullScreenEnabled = {false}` lets the dark background color disappear, I hope you'll fix this one as well😅.

**Comment by david98** [comment]
Hi @ayushmng, I just published version `0.15.0` (it's gonna show up on npm's website in a matter of hours at most, I believe), which adds a `fullScreenImageAspectRatio` prop to override the aspect ratio when going full screen.

As for the other issue you mentioned, could you please open another issue with a bit more detail on that? I'm gonna close this one in the meanwhile :) 

EDIT: also, I noticed that `@shopify/flash-list` was not listed as a peer dependency while it actually should have, so make sure you have installed it in your project (I have updated the README).

**Comment by ayushmng** [comment]
Wow, thank you sooo much for resolving that one, that was really helpful. I'll check out the new version once it's available on npm. Surely I'll create another ticket issue for the other issue.

**Comment by ayushmng** [comment]
Never mind about the second issue, I encountered it during development and mistook it for a bug, my apologies 😁. As for the enhancement suggestion, it would be great if you could allow to add video content also. This would be fantastic for those looking to showcase both images and videos. And, thanks again for your attention to this matter!

**Comment by ayushmng** [comment]
@david98 how long would the new update take to be available in npm?

**Comment by david98** [comment]
Yeaaaaah about that... turns out I was just really tired and the package went to the wrong registry...

Should be live on NPM now :)

**Comment by ayushmng** [comment]
Wow, I just updated this new version, and it is working like a gem😍
